# user_settings.toml

[project]
path = ""
source_file_name = ""

[zmac]
path = ""
output_hex_file = false
expand_macros = false
expand_include_files = false
expand_if = false
omit_symbol_table = false
allow_8080_instructions = false

[mame]
path = ""
debug_mode = false
window_mode = true
skip_game_info = true
bally_pro_arcade = true
bally_home_library_computer = false
bally_computer_system = false
